-- MySQL Script generated by MySQL Workbench
-- Thu 03 Dec 2020 03:50:50 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`approval`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`approval` ;

CREATE TABLE IF NOT EXISTS `mydb`.`approval` (
  `signupid` INT NOT NULL,
  `approval` VARCHAR(45) NULL,
  PRIMARY KEY (`signupid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `pass` VARCHAR(128) NOT NULL,
  `mail` VARCHAR(254) NOT NULL,
  `created` INT(11) NOT NULL,
  `access` INT(11) NOT NULL,
  `login` INT(11) NOT NULL,
  `status` TINYINT(4) NOT NULL,
  `picture` DECIMAL(254) NULL,
  `data` LONGBLOB NULL,
  `admin_signupid` INT NOT NULL,
  PRIMARY KEY (`uid`),
  INDEX `fk_users_admin1_idx` (`admin_signupid` ASC) VISIBLE,
  CONSTRAINT `fk_users_admin1`
    FOREIGN KEY (`admin_signupid`)
    REFERENCES `mydb`.`approval` (`signupid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sessions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sessions` (
  `uid` INT NOT NULL,
  `sid` VARCHAR(128) NOT NULL,
  `ssid` VARCHAR(128) NOT NULL,
  `hostname` VARCHAR(128) NOT NULL,
  `timestamp` INT(11) NOT NULL,
  `cache` INT(11) NOT NULL,
  `session` LONGBLOB NULL,
  PRIMARY KEY (`sid`, `ssid`),
  INDEX `fk_sessions_users_idx` (`uid` ASC) VISIBLE,
  CONSTRAINT `fk_sessions_users`
    FOREIGN KEY (`uid`)
    REFERENCES `mydb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`watchdog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`watchdog` ;

CREATE TABLE IF NOT EXISTS `mydb`.`watchdog` (
  `wid` INT NOT NULL,
  `users_uid` INT NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `message` LONGTEXT NOT NULL,
  `variables` LONGBLOB NOT NULL,
  `severity` TINYINT(3) NOT NULL,
  `link` VARCHAR(255) NULL,
  `location` TEXT(64) NOT NULL,
  `hostname` VARCHAR(128) NOT NULL,
  `timestamp` INT(11) NOT NULL,
  PRIMARY KEY (`wid`),
  INDEX `fk_watchdog_users1_idx` (`users_uid` ASC) VISIBLE,
  CONSTRAINT `fk_watchdog_users1`
    FOREIGN KEY (`users_uid`)
    REFERENCES `mydb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee_type` (
  `tid` INT(12) NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`tid`),
  UNIQUE INDEX `tid_UNIQUE` (`tid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `eid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `salary` INT(12) NULL,
  `address` VARCHAR(45) NULL,
  `employee_type_tid` INT(12) NOT NULL,
  PRIMARY KEY (`eid`),
  UNIQUE INDEX `typeid_UNIQUE` (`eid` ASC) VISIBLE,
  INDEX `fk_employee_employee_type1_idx` (`employee_type_tid` ASC) VISIBLE,
  CONSTRAINT `fk_employee_employee_type1`
    FOREIGN KEY (`employee_type_tid`)
    REFERENCES `mydb`.`employee_type` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_isa_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_isa_employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_isa_employee` (
  `users_uid` INT NOT NULL,
  `employee_eid` INT NOT NULL,
  PRIMARY KEY (`users_uid`, `employee_eid`),
  INDEX `fk_users_has_employee_employee1_idx` (`employee_eid` ASC) VISIBLE,
  INDEX `fk_users_has_employee_users1_idx` (`users_uid` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_employee_users1`
    FOREIGN KEY (`users_uid`)
    REFERENCES `mydb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_employee_employee1`
    FOREIGN KEY (`employee_eid`)
    REFERENCES `mydb`.`employee` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `idaddress` INT NOT NULL,
  `xcoords` BIGINT(30) NULL,
  `ycoords` BIGINT(30) NULL,
  `apiresponse` VARCHAR(45) NULL,
  PRIMARY KEY (`idaddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organisation_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`organisation_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`organisation_type` (
  `oid` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`oid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`organisation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`organisation` (
  `oid` INT NOT NULL,
  `address_idaddress` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `created` VARCHAR(45) NOT NULL,
  `organisation_type_oid` INT NOT NULL,
  PRIMARY KEY (`oid`),
  INDEX `fk_organisation_address1_idx` (`address_idaddress` ASC) VISIBLE,
  INDEX `fk_organisation_organisation_type1_idx` (`organisation_type_oid` ASC) VISIBLE,
  CONSTRAINT `fk_organisation_address1`
    FOREIGN KEY (`address_idaddress`)
    REFERENCES `mydb`.`address` (`idaddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organisation_organisation_type1`
    FOREIGN KEY (`organisation_type_oid`)
    REFERENCES `mydb`.`organisation_type` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organisation_has_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`organisation_has_employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`organisation_has_employee` (
  `organisation_oid` INT NOT NULL,
  `employee_eid` INT NOT NULL,
  `hired` INT(11) NULL,
  `fired` VARCHAR(45) NULL,
  `active` VARCHAR(45) NULL,
  PRIMARY KEY (`organisation_oid`, `employee_eid`),
  INDEX `fk_organisation_has_employee_employee1_idx` (`employee_eid` ASC) VISIBLE,
  INDEX `fk_organisation_has_employee_organisation1_idx` (`organisation_oid` ASC) VISIBLE,
  CONSTRAINT `fk_organisation_has_employee_organisation1`
    FOREIGN KEY (`organisation_oid`)
    REFERENCES `mydb`.`organisation` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organisation_has_employee_employee1`
    FOREIGN KEY (`employee_eid`)
    REFERENCES `mydb`.`employee` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`schedule` ;

CREATE TABLE IF NOT EXISTS `mydb`.`schedule` (
  `schid` INT NOT NULL,
  `week` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `time` TIME NULL,
  PRIMARY KEY (`schid`),
  UNIQUE INDEX `week_UNIQUE` (`week` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee_has_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee_has_schedule` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee_has_schedule` (
  `employee_eid` INT NOT NULL,
  `schedule_schid` INT NOT NULL,
  PRIMARY KEY (`employee_eid`, `schedule_schid`),
  INDEX `fk_employee_has_schedule_schedule1_idx` (`schedule_schid` ASC) VISIBLE,
  INDEX `fk_employee_has_schedule_employee1_idx` (`employee_eid` ASC) VISIBLE,
  CONSTRAINT `fk_employee_has_schedule_employee1`
    FOREIGN KEY (`employee_eid`)
    REFERENCES `mydb`.`employee` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_schedule_schedule1`
    FOREIGN KEY (`schedule_schid`)
    REFERENCES `mydb`.`schedule` (`schid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organisation_has_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`organisation_has_schedule` ;

CREATE TABLE IF NOT EXISTS `mydb`.`organisation_has_schedule` (
  `organisation_oid` INT NOT NULL,
  `schedule_schid` INT NOT NULL,
  PRIMARY KEY (`organisation_oid`, `schedule_schid`),
  INDEX `fk_organisation_has_schedule_schedule1_idx` (`schedule_schid` ASC) VISIBLE,
  INDEX `fk_organisation_has_schedule_organisation1_idx` (`organisation_oid` ASC) VISIBLE,
  CONSTRAINT `fk_organisation_has_schedule_organisation1`
    FOREIGN KEY (`organisation_oid`)
    REFERENCES `mydb`.`organisation` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organisation_has_schedule_schedule1`
    FOREIGN KEY (`schedule_schid`)
    REFERENCES `mydb`.`schedule` (`schid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`report` ;

CREATE TABLE IF NOT EXISTS `mydb`.`report` (
  `rid` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`rid`),
  UNIQUE INDEX `rid_UNIQUE` (`rid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee_creates_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee_creates_report` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee_creates_report` (
  `employee_eid` INT NOT NULL,
  `report_rid` INT NOT NULL,
  PRIMARY KEY (`employee_eid`, `report_rid`),
  INDEX `fk_employee_has_report_report1_idx` (`report_rid` ASC) VISIBLE,
  INDEX `fk_employee_has_report_employee1_idx` (`employee_eid` ASC) VISIBLE,
  CONSTRAINT `fk_employee_has_report_employee1`
    FOREIGN KEY (`employee_eid`)
    REFERENCES `mydb`.`employee` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_report_report1`
    FOREIGN KEY (`report_rid`)
    REFERENCES `mydb`.`report` (`rid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organisation_has_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`organisation_has_report` ;

CREATE TABLE IF NOT EXISTS `mydb`.`organisation_has_report` (
  `organisation_oid` INT NOT NULL,
  `report_rid` INT NOT NULL,
  PRIMARY KEY (`organisation_oid`, `report_rid`),
  INDEX `fk_organisation_has_report_report1_idx` (`report_rid` ASC) VISIBLE,
  INDEX `fk_organisation_has_report_organisation1_idx` (`organisation_oid` ASC) VISIBLE,
  CONSTRAINT `fk_organisation_has_report_organisation1`
    FOREIGN KEY (`organisation_oid`)
    REFERENCES `mydb`.`organisation` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organisation_has_report_report1`
    FOREIGN KEY (`report_rid`)
    REFERENCES `mydb`.`report` (`rid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient_type` (
  `ptid` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`ptid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `patient_type_ptid` INT NOT NULL,
  PRIMARY KEY (`pid`),
  INDEX `fk_patient_patient_type1_idx` (`patient_type_ptid` ASC) VISIBLE,
  CONSTRAINT `fk_patient_patient_type1`
    FOREIGN KEY (`patient_type_ptid`)
    REFERENCES `mydb`.`patient_type` (`ptid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient_mentioned_in_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient_mentioned_in_report` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient_mentioned_in_report` (
  `patient_pid` INT NOT NULL,
  `report_rid` INT NOT NULL,
  PRIMARY KEY (`patient_pid`, `report_rid`),
  INDEX `fk_patient_has_report_report1_idx` (`report_rid` ASC) VISIBLE,
  INDEX `fk_patient_has_report_patient1_idx` (`patient_pid` ASC) VISIBLE,
  CONSTRAINT `fk_patient_has_report_patient1`
    FOREIGN KEY (`patient_pid`)
    REFERENCES `mydb`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_has_report_report1`
    FOREIGN KEY (`report_rid`)
    REFERENCES `mydb`.`report` (`rid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_isa_patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_isa_patient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_isa_patient` (
  `users_uid` INT NOT NULL,
  `patient_pid` INT NOT NULL,
  PRIMARY KEY (`users_uid`, `patient_pid`),
  INDEX `fk_users_has_patient_patient1_idx` (`patient_pid` ASC) VISIBLE,
  INDEX `fk_users_has_patient_users1_idx` (`users_uid` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_patient_users1`
    FOREIGN KEY (`users_uid`)
    REFERENCES `mydb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_patient_patient1`
    FOREIGN KEY (`patient_pid`)
    REFERENCES `mydb`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`appointment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`appointment` (
  `aid` INT NOT NULL,
  `length` INT NULL,
  `notes` VARCHAR(45) NULL,
  `charge` FLOAT NULL,
  PRIMARY KEY (`aid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee_has_appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee_has_appointment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee_has_appointment` (
  `employee_eid` INT NOT NULL,
  `appointment_aid` INT NOT NULL,
  PRIMARY KEY (`employee_eid`, `appointment_aid`),
  INDEX `fk_employee_has_appointment_appointment1_idx` (`appointment_aid` ASC) VISIBLE,
  INDEX `fk_employee_has_appointment_employee1_idx` (`employee_eid` ASC) VISIBLE,
  CONSTRAINT `fk_employee_has_appointment_employee1`
    FOREIGN KEY (`employee_eid`)
    REFERENCES `mydb`.`employee` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_appointment_appointment1`
    FOREIGN KEY (`appointment_aid`)
    REFERENCES `mydb`.`appointment` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient_has_appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient_has_appointment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient_has_appointment` (
  `patient_pid` INT NOT NULL,
  `appointment_aid` INT NOT NULL,
  PRIMARY KEY (`patient_pid`, `appointment_aid`),
  INDEX `fk_patient_has_appointment_appointment1_idx` (`appointment_aid` ASC) VISIBLE,
  INDEX `fk_patient_has_appointment_patient1_idx` (`patient_pid` ASC) VISIBLE,
  CONSTRAINT `fk_patient_has_appointment_patient1`
    FOREIGN KEY (`patient_pid`)
    REFERENCES `mydb`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_has_appointment_appointment1`
    FOREIGN KEY (`appointment_aid`)
    REFERENCES `mydb`.`appointment` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule_has_appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`schedule_has_appointment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`schedule_has_appointment` (
  `appointment_aid` INT NOT NULL,
  `schedule_schid` INT NOT NULL,
  PRIMARY KEY (`appointment_aid`, `schedule_schid`),
  INDEX `fk_appointment_has_schedule_schedule1_idx` (`schedule_schid` ASC) VISIBLE,
  INDEX `fk_appointment_has_schedule_appointment1_idx` (`appointment_aid` ASC) VISIBLE,
  CONSTRAINT `fk_appointment_has_schedule_appointment1`
    FOREIGN KEY (`appointment_aid`)
    REFERENCES `mydb`.`appointment` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_has_schedule_schedule1`
    FOREIGN KEY (`schedule_schid`)
    REFERENCES `mydb`.`schedule` (`schid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`report_has_appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`report_has_appointment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`report_has_appointment` (
  `report_rid` INT NOT NULL,
  `appointment_aid` INT NOT NULL,
  PRIMARY KEY (`report_rid`, `appointment_aid`),
  INDEX `fk_report_has_appointment_appointment1_idx` (`appointment_aid` ASC) VISIBLE,
  INDEX `fk_report_has_appointment_report1_idx` (`report_rid` ASC) VISIBLE,
  CONSTRAINT `fk_report_has_appointment_report1`
    FOREIGN KEY (`report_rid`)
    REFERENCES `mydb`.`report` (`rid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_has_appointment_appointment1`
    FOREIGN KEY (`appointment_aid`)
    REFERENCES `mydb`.`appointment` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prescription` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prescription` (
  `prsid` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`prsid`),
  UNIQUE INDEX `prsid_UNIQUE` (`prsid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee_creates_prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee_creates_prescription` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee_creates_prescription` (
  `employee_eid` INT NOT NULL,
  `prescription_prsid` INT NOT NULL,
  PRIMARY KEY (`employee_eid`, `prescription_prsid`),
  INDEX `fk_employee_has_prescription_prescription1_idx` (`prescription_prsid` ASC) VISIBLE,
  INDEX `fk_employee_has_prescription_employee1_idx` (`employee_eid` ASC) VISIBLE,
  CONSTRAINT `fk_employee_has_prescription_employee1`
    FOREIGN KEY (`employee_eid`)
    REFERENCES `mydb`.`employee` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_prescription_prescription1`
    FOREIGN KEY (`prescription_prsid`)
    REFERENCES `mydb`.`prescription` (`prsid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient_has_prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient_has_prescription` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient_has_prescription` (
  `patient_pid` INT NOT NULL,
  `prescription_prsid` INT NOT NULL,
  PRIMARY KEY (`patient_pid`, `prescription_prsid`),
  INDEX `fk_patient_has_prescription_prescription1_idx` (`prescription_prsid` ASC) VISIBLE,
  INDEX `fk_patient_has_prescription_patient1_idx` (`patient_pid` ASC) VISIBLE,
  CONSTRAINT `fk_patient_has_prescription_patient1`
    FOREIGN KEY (`patient_pid`)
    REFERENCES `mydb`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_has_prescription_prescription1`
    FOREIGN KEY (`prescription_prsid`)
    REFERENCES `mydb`.`prescription` (`prsid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`calendar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`calendar` (
  `idcalendar` INT NOT NULL,
  `appointment_aid` INT NOT NULL,
  `schedule_has_appointment_appointment_aid` INT NOT NULL,
  `schedule_has_appointment_schedule_schid` INT NOT NULL,
  PRIMARY KEY (`idcalendar`),
  INDEX `fk_calendar_appointment1_idx` (`appointment_aid` ASC) VISIBLE,
  INDEX `fk_calendar_schedule_has_appointment1_idx` (`schedule_has_appointment_appointment_aid` ASC, `schedule_has_appointment_schedule_schid` ASC) VISIBLE,
  CONSTRAINT `fk_calendar_appointment1`
    FOREIGN KEY (`appointment_aid`)
    REFERENCES `mydb`.`appointment` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendar_schedule_has_appointment1`
    FOREIGN KEY (`schedule_has_appointment_appointment_aid` , `schedule_has_appointment_schedule_schid`)
    REFERENCES `mydb`.`schedule_has_appointment` (`appointment_aid` , `schedule_schid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `idrole` INT NOT NULL,
  `rolepermission` VARCHAR(45) NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blocked_ips`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blocked_ips` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blocked_ips` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cache`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cache` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cache` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
