-- MySQL Script generated by MySQL Workbench
-- Sat Dec 12 02:03:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema root
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema root
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `root` ;
USE `root` ;

-- -----------------------------------------------------
-- Table `root`.`user_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`user_status` (
  `usid` INT NOT NULL AUTO_INCREMENT,
  `user_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usid`),
  UNIQUE INDEX `usid_UNIQUE` (`usid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`users` (
  `uuid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(40) NOT NULL,
  `pass` VARCHAR(40) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `created` DATETIME NOT NULL,
  `last_access` DATETIME NOT NULL,
  `logged_in` INT NOT NULL,
  `picture` VARCHAR(128) NOT NULL,
  `user_status_usid` INT NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_users_user_status1_idx` (`user_status_usid` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  CONSTRAINT `fk_users_user_status1`
    FOREIGN KEY (`user_status_usid`)
    REFERENCES `root`.`user_status` (`usid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`watchdog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`watchdog` (
  `wid` INT NOT NULL AUTO_INCREMENT,
  `users_uid` INT NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `message` LONGTEXT NOT NULL,
  `timestamp` INT(11) NOT NULL,
  PRIMARY KEY (`wid`),
  INDEX `fk_watchdog_users1_idx` (`users_uid` ASC) VISIBLE,
  UNIQUE INDEX `wid_UNIQUE` (`wid` ASC) VISIBLE,
  CONSTRAINT `fk_watchdog_users1`
    FOREIGN KEY (`users_uid`)
    REFERENCES `root`.`users` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`employee_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`employee_type` (
  `etid` INT(12) NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`etid`),
  UNIQUE INDEX `etid_UNIQUE` (`etid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`organisation_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`organisation_type` (
  `otid` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`otid`),
  UNIQUE INDEX `otid_UNIQUE` (`otid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`organisation` (
  `oid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `organisation_type_oid` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`oid`),
  INDEX `fk_organisation_organisation_type1_idx` (`organisation_type_oid` ASC) VISIBLE,
  UNIQUE INDEX `oid_UNIQUE` (`oid` ASC) VISIBLE,
  CONSTRAINT `fk_organisation_organisation_type1`
    FOREIGN KEY (`organisation_type_oid`)
    REFERENCES `root`.`organisation_type` (`otid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`employee` (
  `eid` INT NOT NULL AUTO_INCREMENT,
  `salary` DOUBLE NOT NULL,
  `address` VARCHAR(40) NOT NULL,
  `employee_type_tid` INT NOT NULL,
  `organisation_oid` INT NOT NULL,
  `users_uuid` INT NOT NULL,
  PRIMARY KEY (`eid`),
  INDEX `fk_employee_employee_type1_idx` (`employee_type_tid` ASC) VISIBLE,
  INDEX `fk_employee_organisation1_idx` (`organisation_oid` ASC) VISIBLE,
  INDEX `fk_employee_users1_idx` (`users_uuid` ASC) VISIBLE,
  UNIQUE INDEX `eid_UNIQUE` (`eid` ASC) VISIBLE,
  CONSTRAINT `fk_employee_employee_type1`
    FOREIGN KEY (`employee_type_tid`)
    REFERENCES `root`.`employee_type` (`etid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_organisation1`
    FOREIGN KEY (`organisation_oid`)
    REFERENCES `root`.`organisation` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_users1`
    FOREIGN KEY (`users_uuid`)
    REFERENCES `root`.`users` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`patient_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`patient_type` (
  `ptid` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ptid`),
  UNIQUE INDEX `ptid_UNIQUE` (`ptid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`patient` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `patient_type_ptid` INT NOT NULL,
  `users_uuid` INT NOT NULL,
  PRIMARY KEY (`pid`),
  INDEX `fk_patient_patient_type1_idx` (`patient_type_ptid` ASC) VISIBLE,
  INDEX `fk_patient_users1_idx` (`users_uuid` ASC) VISIBLE,
  UNIQUE INDEX `pid_UNIQUE` (`pid` ASC) VISIBLE,
  CONSTRAINT `fk_patient_patient_type1`
    FOREIGN KEY (`patient_type_ptid`)
    REFERENCES `root`.`patient_type` (`ptid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_users1`
    FOREIGN KEY (`users_uuid`)
    REFERENCES `root`.`users` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`patient_prescriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`patient_prescriptions` (
  `prid` INT NOT NULL AUTO_INCREMENT,
  `patient_pid` INT NOT NULL,
  `medicine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`prid`),
  INDEX `fk_patient_records_patient1_idx` (`patient_pid` ASC) VISIBLE,
  UNIQUE INDEX `prid_UNIQUE` (`prid` ASC) VISIBLE,
  CONSTRAINT `fk_patient_records_patient1`
    FOREIGN KEY (`patient_pid`)
    REFERENCES `root`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`appointment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`appointment_type` (
  `atid` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`atid`),
  UNIQUE INDEX `atid_UNIQUE` (`atid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`appointment_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`appointment_status` (
  `asid` INT NOT NULL AUTO_INCREMENT,
  `appointment_status` VARCHAR(45) NULL,
  PRIMARY KEY (`asid`),
  UNIQUE INDEX `asid_UNIQUE` (`asid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`appointment` (
  `aid` INT NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `duration` INT NOT NULL,
  `notes` VARCHAR(45) NOT NULL,
  `charge` DOUBLE NOT NULL,
  `patient_pid` INT NOT NULL,
  `employee_eid` INT NOT NULL,
  `appointment_type_atid` INT NOT NULL,
  `patient_prescriptions_prid` INT NOT NULL,
  `appointment_status_asid` INT NOT NULL,
  PRIMARY KEY (`aid`),
  INDEX `fk_appointment_patient1_idx` (`patient_pid` ASC) VISIBLE,
  INDEX `fk_appointment_employee1_idx` (`employee_eid` ASC) VISIBLE,
  INDEX `fk_appointment_patient_prescriptions1_idx` (`patient_prescriptions_prid` ASC) VISIBLE,
  INDEX `fk_appointment_appointment_type1_idx` (`appointment_type_atid` ASC) VISIBLE,
  INDEX `fk_appointment_appointment_status1_idx` (`appointment_status_asid` ASC) VISIBLE,
  UNIQUE INDEX `aid_UNIQUE` (`aid` ASC) VISIBLE,
  CONSTRAINT `fk_appointment_patient1`
    FOREIGN KEY (`patient_pid`)
    REFERENCES `root`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_employee1`
    FOREIGN KEY (`employee_eid`)
    REFERENCES `root`.`employee` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_patient_prescriptions1`
    FOREIGN KEY (`patient_prescriptions_prid`)
    REFERENCES `root`.`patient_prescriptions` (`prid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_appointment_type1`
    FOREIGN KEY (`appointment_type_atid`)
    REFERENCES `root`.`appointment_type` (`atid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_appointment_status1`
    FOREIGN KEY (`appointment_status_asid`)
    REFERENCES `root`.`appointment_status` (`asid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `root`.`future_appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `root`.`future_appointments` (
  `faid` INT NOT NULL AUTO_INCREMENT,
  `future_start_time` DATETIME NOT NULL,
  `future_end_time` DATETIME NOT NULL,
  `duration` INT NOT NULL,
  `patient_pid` INT NOT NULL,
  `employee_eid` INT NOT NULL,
  PRIMARY KEY (`faid`),
  INDEX `fk_future_appointments_patient1_idx` (`patient_pid` ASC) VISIBLE,
  INDEX `fk_future_appointments_employee1_idx` (`employee_eid` ASC) VISIBLE,
  UNIQUE INDEX `faid_UNIQUE` (`faid` ASC) VISIBLE,
  CONSTRAINT `fk_future_appointments_patient1`
    FOREIGN KEY (`patient_pid`)
    REFERENCES `root`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_future_appointments_employee1`
    FOREIGN KEY (`employee_eid`)
    REFERENCES `root`.`employee` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
