CREATE TABLE ADDRESS ( 
	IDADDRESS            integer NOT NULL  ,
	XCOORDS              bigint   ,
	YCOORDS              bigint   ,
	APIRESPONSE          varchar(45)   ,
	CONSTRAINT PK_ADDRESS PRIMARY KEY ( IDADDRESS )
 );

CREATE TABLE APPOINTMENT ( 
	AID                  integer NOT NULL  ,
	LENGTH               integer   ,
	NOTES                varchar(45)   ,
	CHARGE               double   ,
	CONSTRAINT PRIMARY1 PRIMARY KEY ( AID )
 );

CREATE TABLE APPROVAL ( 
	SIGNUPID             integer NOT NULL  ,
	APPROVAL             varchar(45)   ,
	CONSTRAINT PRIMARY2 PRIMARY KEY ( SIGNUPID )
 );

CREATE TABLE EMPLOYEE_TYPE ( 
	TID                  integer NOT NULL  ,
	TYPE_NAME            varchar(45)   ,
	CONSTRAINT PRIMARY3 PRIMARY KEY ( TID )
 );

CREATE TABLE ORGANISATION_TYPE ( 
	OID                  integer NOT NULL  ,
	TYPE_NAME            varchar(45)   ,
	CONSTRAINT PRIMARY12 PRIMARY KEY ( OID )
 );

CREATE TABLE PATIENT_TYPE ( 
	PTID                 integer NOT NULL  ,
	TYPE_NAME            varchar(45)   ,
	CONSTRAINT PRIMARY17 PRIMARY KEY ( PTID )
 );

CREATE TABLE PRESCRIPTION ( 
	PRSID                integer NOT NULL  ,
	CONSTRAINT PRIMARY5 PRIMARY KEY ( PRSID )
 );

CREATE TABLE REPORT ( 
	RID                  integer NOT NULL  ,
	CONSTRAINT PRIMARY7 PRIMARY KEY ( RID )
 );

CREATE TABLE REPORT_HAS_APPOINTMENT ( 
	REPORT_RID           integer NOT NULL  ,
	APPOINTMENT_AID      integer NOT NULL  ,
	CONSTRAINT PRIMARY22 PRIMARY KEY ( REPORT_RID, APPOINTMENT_AID )
 );

CREATE INDEX SQL201210191701992 ON REPORT_HAS_APPOINTMENT ( APPOINTMENT_AID );

CREATE INDEX SQL201210191702112 ON REPORT_HAS_APPOINTMENT ( REPORT_RID );

CREATE TABLE ROLE ( 
	IDROLE               integer NOT NULL  ,
	ROLEPERMISSION       varchar(45)   ,
	CONSTRAINT PRIMARY23 PRIMARY KEY ( IDROLE )
 );

CREATE TABLE SCHEDULE ( 
	SCHID                integer NOT NULL  ,
	WEEK                 integer NOT NULL  ,
	DATE                 date   ,
	TIME                 time   ,
	CONSTRAINT PRIMARY10 PRIMARY KEY ( SCHID ),
	CONSTRAINT WEEK_UNIQUE UNIQUE ( WEEK ) 
 );

CREATE TABLE SCHEDULE_HAS_APPOINTMENT ( 
	APPOINTMENT_AID      integer NOT NULL  ,
	SCHEDULE_SCHID       integer NOT NULL  ,
	CONSTRAINT PRIMARY24 PRIMARY KEY ( APPOINTMENT_AID, SCHEDULE_SCHID )
 );

CREATE INDEX SQL201210191701993 ON SCHEDULE_HAS_APPOINTMENT ( APPOINTMENT_AID );

CREATE INDEX SQL201210191702120 ON SCHEDULE_HAS_APPOINTMENT ( SCHEDULE_SCHID );

CREATE TABLE USERS ( 
	UID                  integer NOT NULL  ,
	NAME                 varchar(60) NOT NULL  ,
	PASS                 varchar(128) NOT NULL  ,
	MAIL                 varchar(254) NOT NULL  ,
	CREATED              integer NOT NULL  ,
	ACCESS               integer NOT NULL  ,
	LOGIN                integer NOT NULL  ,
	STATUS               smallint NOT NULL  ,
	PICTURE              varchar(64)   ,
	DATA                 blob   ,
	ADMIN_SIGNUPID       integer NOT NULL  ,
	CONSTRAINT PRIMARY25 PRIMARY KEY ( UID )
 );

CREATE INDEX SQL201210191701880 ON USERS ( ADMIN_SIGNUPID );

CREATE TABLE WATCHDOG ( 
	USERS_UID            integer NOT NULL  ,
	TYPE                 varchar(64) NOT NULL  ,
	MESSAGE              clob(2147483647) NOT NULL  ,
	VARIABLES            blob NOT NULL  ,
	SEVERITY             smallint NOT NULL  ,
	LINK                 varchar(255)   ,
	LOCATION             clob(2147483647) NOT NULL  ,
	HOSTNAME             varchar(128) NOT NULL  ,
	TIMESTAMP            integer NOT NULL  
 );

CREATE INDEX SQL201210191701882 ON WATCHDOG ( USERS_UID );

CREATE TABLE EMPLOYEE ( 
	EID                  integer NOT NULL  ,
	NAME                 varchar(45)   ,
	SALARY               integer   ,
	ADDRESS              varchar(45)   ,
	EMPLOYEE_TYPE_TID    integer NOT NULL  ,
	CONSTRAINT PRIMARY4 PRIMARY KEY ( EID )
 );

CREATE INDEX SQL201210191701850 ON EMPLOYEE ( EMPLOYEE_TYPE_TID );

CREATE TABLE EMPLOYEE_CREATES_PRESCRIPTION ( 
	EMPLOYEE_EID         integer NOT NULL  ,
	PRESCRIPTION_PRSID   integer NOT NULL  ,
	CONSTRAINT PRIMARY6 PRIMARY KEY ( EMPLOYEE_EID, PRESCRIPTION_PRSID )
 );

CREATE INDEX SQL201210191701950 ON EMPLOYEE_CREATES_PRESCRIPTION ( EMPLOYEE_EID );

CREATE INDEX SQL201210191702060 ON EMPLOYEE_CREATES_PRESCRIPTION ( PRESCRIPTION_PRSID );

CREATE TABLE EMPLOYEE_CREATES_REPORT ( 
	EMPLOYEE_EID         integer NOT NULL  ,
	REPORT_RID           integer NOT NULL  ,
	CONSTRAINT PRIMARY8 PRIMARY KEY ( EMPLOYEE_EID, REPORT_RID )
 );

CREATE INDEX SQL201210191701960 ON EMPLOYEE_CREATES_REPORT ( EMPLOYEE_EID );

CREATE INDEX SQL201210191702070 ON EMPLOYEE_CREATES_REPORT ( REPORT_RID );

CREATE TABLE EMPLOYEE_HAS_APPOINTMENT ( 
	EMPLOYEE_EID         integer NOT NULL  ,
	APPOINTMENT_AID      integer NOT NULL  ,
	CONSTRAINT PRIMARY9 PRIMARY KEY ( EMPLOYEE_EID, APPOINTMENT_AID )
 );

CREATE INDEX SQL201210191701961 ON EMPLOYEE_HAS_APPOINTMENT ( APPOINTMENT_AID );

CREATE INDEX SQL201210191702071 ON EMPLOYEE_HAS_APPOINTMENT ( EMPLOYEE_EID );

CREATE TABLE EMPLOYEE_HAS_SCHEDULE ( 
	EMPLOYEE_EID         integer NOT NULL  ,
	SCHEDULE_SCHID       integer NOT NULL  ,
	CONSTRAINT PRIMARY11 PRIMARY KEY ( EMPLOYEE_EID, SCHEDULE_SCHID )
 );

CREATE INDEX SQL201210191701970 ON EMPLOYEE_HAS_SCHEDULE ( EMPLOYEE_EID );

CREATE INDEX SQL201210191702080 ON EMPLOYEE_HAS_SCHEDULE ( SCHEDULE_SCHID );

CREATE TABLE ORGANISATION ( 
	OID                  integer NOT NULL  ,
	ADDRESS_IDADDRESS    integer NOT NULL  ,
	NAME                 varchar(45) NOT NULL  ,
	CREATED              varchar(45) NOT NULL  ,
	ORGANISATION_TYPE_OID integer NOT NULL  ,
	CONSTRAINT PRIMARY13 PRIMARY KEY ( OID )
 );

CREATE INDEX SQL201210191701971 ON ORGANISATION ( ADDRESS_IDADDRESS );

CREATE INDEX SQL201210191702081 ON ORGANISATION ( ORGANISATION_TYPE_OID );

CREATE TABLE ORGANISATION_HAS_EMPLOYEE ( 
	ORGANISATION_OID     integer NOT NULL  ,
	EMPLOYEE_EID         integer NOT NULL  ,
	HIRED                integer   ,
	FIRED                varchar(45)   ,
	ACTIVE               varchar(45)   ,
	CONSTRAINT PRIMARY14 PRIMARY KEY ( ORGANISATION_OID, EMPLOYEE_EID )
 );

CREATE INDEX SQL201210191701972 ON ORGANISATION_HAS_EMPLOYEE ( EMPLOYEE_EID );

CREATE INDEX SQL201210191702082 ON ORGANISATION_HAS_EMPLOYEE ( ORGANISATION_OID );

CREATE TABLE ORGANISATION_HAS_REPORT ( 
	ORGANISATION_OID     integer NOT NULL  ,
	REPORT_RID           integer NOT NULL  ,
	CONSTRAINT PRIMARY15 PRIMARY KEY ( ORGANISATION_OID, REPORT_RID )
 );

CREATE INDEX SQL201210191701980 ON ORGANISATION_HAS_REPORT ( ORGANISATION_OID );

CREATE INDEX SQL201210191702090 ON ORGANISATION_HAS_REPORT ( REPORT_RID );

CREATE TABLE ORGANISATION_HAS_SCHEDULE ( 
	ORGANISATION_OID     integer NOT NULL  ,
	SCHEDULE_SCHID       integer NOT NULL  ,
	CONSTRAINT PRIMARY16 PRIMARY KEY ( ORGANISATION_OID, SCHEDULE_SCHID )
 );

CREATE INDEX SQL201210191701981 ON ORGANISATION_HAS_SCHEDULE ( ORGANISATION_OID );

CREATE INDEX SQL201210191702100 ON ORGANISATION_HAS_SCHEDULE ( SCHEDULE_SCHID );

CREATE TABLE PATIENT ( 
	PID                  integer NOT NULL  ,
	NAME                 varchar(45)   ,
	ADDRESS              varchar(45)   ,
	PATIENT_TYPE_PTID    integer NOT NULL  ,
	CONSTRAINT PRIMARY18 PRIMARY KEY ( PID )
 );

CREATE INDEX SQL201210191701870 ON PATIENT ( PATIENT_TYPE_PTID );

CREATE TABLE PATIENT_HAS_APPOINTMENT ( 
	PATIENT_PID          integer NOT NULL  ,
	APPOINTMENT_AID      integer NOT NULL  ,
	CONSTRAINT PRIMARY19 PRIMARY KEY ( PATIENT_PID, APPOINTMENT_AID )
 );

CREATE INDEX SQL201210191701982 ON PATIENT_HAS_APPOINTMENT ( APPOINTMENT_AID );

CREATE INDEX SQL201210191702101 ON PATIENT_HAS_APPOINTMENT ( PATIENT_PID );

CREATE TABLE PATIENT_HAS_PRESCRIPTION ( 
	PATIENT_PID          integer NOT NULL  ,
	PRESCRIPTION_PRSID   integer NOT NULL  ,
	CONSTRAINT PRIMARY20 PRIMARY KEY ( PATIENT_PID, PRESCRIPTION_PRSID )
 );

CREATE INDEX SQL201210191701990 ON PATIENT_HAS_PRESCRIPTION ( PATIENT_PID );

CREATE INDEX SQL201210191702110 ON PATIENT_HAS_PRESCRIPTION ( PRESCRIPTION_PRSID );

CREATE TABLE PATIENT_MENTIONED_IN_REPORT ( 
	PATIENT_PID          integer NOT NULL  ,
	REPORT_RID           integer NOT NULL  ,
	CONSTRAINT PRIMARY21 PRIMARY KEY ( PATIENT_PID, REPORT_RID )
 );

CREATE INDEX SQL201210191701991 ON PATIENT_MENTIONED_IN_REPORT ( PATIENT_PID );

CREATE INDEX SQL201210191702111 ON PATIENT_MENTIONED_IN_REPORT ( REPORT_RID );

CREATE TABLE SESSIONS ( 
	SID                  varchar(128) NOT NULL  ,
	SSID                 varchar(128) NOT NULL  ,
	UID                  integer NOT NULL  ,
	HOSTNAME             varchar(128) NOT NULL  ,
	TIMESTAMP            integer NOT NULL  ,
	CACHE                integer NOT NULL  ,
	SESSION              blob   ,
	CONSTRAINT PRIMARY26 PRIMARY KEY ( SID, SSID )
 );

CREATE INDEX SQL201210191701881 ON SESSIONS ( UID );

CREATE TABLE USERS_ISA_EMPLOYEE ( 
	USERS_UID            integer NOT NULL  ,
	EMPLOYEE_EID         integer NOT NULL  ,
	CONSTRAINT PRIMARY27 PRIMARY KEY ( USERS_UID, EMPLOYEE_EID )
 );

CREATE INDEX SQL201210191702000 ON USERS_ISA_EMPLOYEE ( EMPLOYEE_EID );

CREATE INDEX SQL201210191702121 ON USERS_ISA_EMPLOYEE ( USERS_UID );

CREATE TABLE USERS_ISA_PATIENT ( 
	USERS_UID            integer NOT NULL  ,
	PATIENT_PID          integer NOT NULL  ,
	CONSTRAINT PRIMARY28 PRIMARY KEY ( USERS_UID, PATIENT_PID )
 );

CREATE INDEX SQL201210191702001 ON USERS_ISA_PATIENT ( PATIENT_PID );

CREATE INDEX SQL201210191702130 ON USERS_ISA_PATIENT ( USERS_UID );

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_EMPLOYEE_TYPE1 FOREIGN KEY ( EMPLOYEE_TYPE_TID ) REFERENCES EMPLOYEE_TYPE( TID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE EMPLOYEE_CREATES_PRESCRIPTION ADD CONSTRAINT FK_EMPLOYEE_HAS_PRESCRIPTION_EMPLOYEE1 FOREIGN KEY ( EMPLOYEE_EID ) REFERENCES EMPLOYEE( EID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE EMPLOYEE_CREATES_PRESCRIPTION ADD CONSTRAINT FK_EMPLOYEE_HAS_PRESCRIPTION_PRESCRIPTION1 FOREIGN KEY ( PRESCRIPTION_PRSID ) REFERENCES PRESCRIPTION( PRSID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE EMPLOYEE_CREATES_REPORT ADD CONSTRAINT FK_EMPLOYEE_HAS_REPORT_EMPLOYEE1 FOREIGN KEY ( EMPLOYEE_EID ) REFERENCES EMPLOYEE( EID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE EMPLOYEE_CREATES_REPORT ADD CONSTRAINT FK_EMPLOYEE_HAS_REPORT_REPORT1 FOREIGN KEY ( REPORT_RID ) REFERENCES REPORT( RID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE EMPLOYEE_HAS_APPOINTMENT ADD CONSTRAINT FK_EMPLOYEE_HAS_APPOINTMENT_APPOINTMENT1 FOREIGN KEY ( APPOINTMENT_AID ) REFERENCES APPOINTMENT( AID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE EMPLOYEE_HAS_APPOINTMENT ADD CONSTRAINT FK_EMPLOYEE_HAS_APPOINTMENT_EMPLOYEE1 FOREIGN KEY ( EMPLOYEE_EID ) REFERENCES EMPLOYEE( EID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE EMPLOYEE_HAS_SCHEDULE ADD CONSTRAINT FK_EMPLOYEE_HAS_SCHEDULE_EMPLOYEE1 FOREIGN KEY ( EMPLOYEE_EID ) REFERENCES EMPLOYEE( EID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE EMPLOYEE_HAS_SCHEDULE ADD CONSTRAINT FK_EMPLOYEE_HAS_SCHEDULE_SCHEDULE1 FOREIGN KEY ( SCHEDULE_SCHID ) REFERENCES SCHEDULE( SCHID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ORGANISATION ADD CONSTRAINT FK_ORGANISATION_ADDRESS1 FOREIGN KEY ( ADDRESS_IDADDRESS ) REFERENCES ADDRESS( IDADDRESS ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ORGANISATION ADD CONSTRAINT FK_ORGANISATION_ORGANISATION_TYPE1 FOREIGN KEY ( ORGANISATION_TYPE_OID ) REFERENCES ORGANISATION_TYPE( OID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ORGANISATION_HAS_EMPLOYEE ADD CONSTRAINT FK_ORGANISATION_HAS_EMPLOYEE_EMPLOYEE1 FOREIGN KEY ( EMPLOYEE_EID ) REFERENCES EMPLOYEE( EID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ORGANISATION_HAS_EMPLOYEE ADD CONSTRAINT FK_ORGANISATION_HAS_EMPLOYEE_ORGANISATION1 FOREIGN KEY ( ORGANISATION_OID ) REFERENCES ORGANISATION( OID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ORGANISATION_HAS_REPORT ADD CONSTRAINT FK_ORGANISATION_HAS_REPORT_ORGANISATION1 FOREIGN KEY ( ORGANISATION_OID ) REFERENCES ORGANISATION( OID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ORGANISATION_HAS_REPORT ADD CONSTRAINT FK_ORGANISATION_HAS_REPORT_REPORT1 FOREIGN KEY ( REPORT_RID ) REFERENCES REPORT( RID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ORGANISATION_HAS_SCHEDULE ADD CONSTRAINT FK_ORGANISATION_HAS_SCHEDULE_ORGANISATION1 FOREIGN KEY ( ORGANISATION_OID ) REFERENCES ORGANISATION( OID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ORGANISATION_HAS_SCHEDULE ADD CONSTRAINT FK_ORGANISATION_HAS_SCHEDULE_SCHEDULE1 FOREIGN KEY ( SCHEDULE_SCHID ) REFERENCES SCHEDULE( SCHID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PATIENT ADD CONSTRAINT FK_PATIENT_PATIENT_TYPE1 FOREIGN KEY ( PATIENT_TYPE_PTID ) REFERENCES PATIENT_TYPE( PTID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PATIENT_HAS_APPOINTMENT ADD CONSTRAINT FK_PATIENT_HAS_APPOINTMENT_APPOINTMENT1 FOREIGN KEY ( APPOINTMENT_AID ) REFERENCES APPOINTMENT( AID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PATIENT_HAS_APPOINTMENT ADD CONSTRAINT FK_PATIENT_HAS_APPOINTMENT_PATIENT1 FOREIGN KEY ( PATIENT_PID ) REFERENCES PATIENT( PID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PATIENT_HAS_PRESCRIPTION ADD CONSTRAINT FK_PATIENT_HAS_PRESCRIPTION_PATIENT1 FOREIGN KEY ( PATIENT_PID ) REFERENCES PATIENT( PID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PATIENT_HAS_PRESCRIPTION ADD CONSTRAINT FK_PATIENT_HAS_PRESCRIPTION_PRESCRIPTION1 FOREIGN KEY ( PRESCRIPTION_PRSID ) REFERENCES PRESCRIPTION( PRSID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PATIENT_MENTIONED_IN_REPORT ADD CONSTRAINT FK_PATIENT_HAS_REPORT_PATIENT1 FOREIGN KEY ( PATIENT_PID ) REFERENCES PATIENT( PID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PATIENT_MENTIONED_IN_REPORT ADD CONSTRAINT FK_PATIENT_HAS_REPORT_REPORT1 FOREIGN KEY ( REPORT_RID ) REFERENCES REPORT( RID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE REPORT_HAS_APPOINTMENT ADD CONSTRAINT FK_REPORT_HAS_APPOINTMENT_APPOINTMENT1 FOREIGN KEY ( APPOINTMENT_AID ) REFERENCES APPOINTMENT( AID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE REPORT_HAS_APPOINTMENT ADD CONSTRAINT FK_REPORT_HAS_APPOINTMENT_REPORT1 FOREIGN KEY ( REPORT_RID ) REFERENCES REPORT( RID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEDULE_HAS_APPOINTMENT ADD CONSTRAINT FK_APPOINTMENT_HAS_SCHEDULE_APPOINTMENT1 FOREIGN KEY ( APPOINTMENT_AID ) REFERENCES APPOINTMENT( AID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEDULE_HAS_APPOINTMENT ADD CONSTRAINT FK_APPOINTMENT_HAS_SCHEDULE_SCHEDULE1 FOREIGN KEY ( SCHEDULE_SCHID ) REFERENCES SCHEDULE( SCHID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SESSIONS ADD CONSTRAINT FK_SESSIONS_USERS FOREIGN KEY ( UID ) REFERENCES USERS( UID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE USERS ADD CONSTRAINT FK_USERS_ADMIN1 FOREIGN KEY ( ADMIN_SIGNUPID ) REFERENCES APPROVAL( SIGNUPID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE USERS_ISA_EMPLOYEE ADD CONSTRAINT FK_USERS_HAS_EMPLOYEE_EMPLOYEE1 FOREIGN KEY ( EMPLOYEE_EID ) REFERENCES EMPLOYEE( EID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE USERS_ISA_EMPLOYEE ADD CONSTRAINT FK_USERS_HAS_EMPLOYEE_USERS1 FOREIGN KEY ( USERS_UID ) REFERENCES USERS( UID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE USERS_ISA_PATIENT ADD CONSTRAINT FK_USERS_HAS_PATIENT_PATIENT1 FOREIGN KEY ( PATIENT_PID ) REFERENCES PATIENT( PID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE USERS_ISA_PATIENT ADD CONSTRAINT FK_USERS_HAS_PATIENT_USERS1 FOREIGN KEY ( USERS_UID ) REFERENCES USERS( UID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE WATCHDOG ADD CONSTRAINT FK_WATCHDOG_USERS1 FOREIGN KEY ( USERS_UID ) REFERENCES USERS( UID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

